name: Hello CI code
on: 
 push: 
   branches: ["main"]
 pull_request:
   branches: ["main"]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Print hello world message
       run: echo "hello World!"
