name: Java CICD with gradle
on:
  push: 
     branches: ["main"]
  pull_request:
     branches: ["main"]
jobs:
  build:
     runs-on: ubuntu-latest
     steps: 
       - name: Checkout the code
         uses: actions/checkout@v3
       - name: Setup JDK 21 (Temurin)
         uses: actions/setup-java@v2
         with:
          java-version: '21'
          distribution: 'temurin'
       - name: Cache Gradle dependencies
         uses: actions/cache@v3
         with:
          path: ~/.gradle/wrapper/cache/**/*  # Cache Gradle wrapper cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}  # Hash based on build.gradle file
          restore-keys: |
            ${{ runner.os }}-gradle-

       - name: Build with Gradle
         run: ./gradlew build  # Build the project with Gradle

       - name: Run tests
         run: ./gradlew test  # Run tests with Gradle
