name: Java CICD with maven
on:
  push: 
     branches: ["main"]
  pull_request:
     branches: ["main"]
jobs:
  build:
     runs-on: ubuntu-latest
     steps: 
       - name: Checkout the code
         uses: actions/checkout@v3
       - name: Setup JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'termurin'
       - name: Cache Maven packages
         uses: actions/cache@v3
         with:
           path: ~/.m2
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
       - name: Build with Maven
         run: mvn clean install
       - name: Run tests
         run: mvn test
