name: PR Validation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Temurin supports Java 21
          java-version: '21'       # Use Java 21
      - name: Build and Test
        run: |
          ./gradlew clean build
